import React from 'react';
import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service — ScoutLayer',
};

export default function Terms() {
  return (
    <div className="min-h-screen bg-bg text-text">
      <article className="max-w-2xl mx-auto px-6 py-16">
        <Link href="/" className="text-sm text-text-muted hover:text-action transition-colors mb-8 inline-block">
          ← Back
        </Link>

        <h1 className="font-display text-3xl font-bold tracking-tight mb-2">Terms of Service</h1>
        <p className="font-data text-xs text-text-muted mb-12">Last updated: July 2026</p>

        <div className="flex flex-col gap-10 text-sm text-text-muted leading-relaxed">
          <section>
            <h2 className="font-display text-lg font-semibold text-text mb-3">Overview</h2>
            <p>
              ScoutLayer is a research prototype built for the Hack-Nation 6th Global AI Hackathon
              (Maschmeyer Group — Challenge 02). It is not a production financial product. By using
              this platform, you acknowledge that it is an experimental tool designed to demonstrate
              AI-driven venture sourcing and screening capabilities.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-text mb-3">Use of the Platform</h2>
            <p>
              You may use ScoutLayer to submit founder applications, explore AI-generated screening
              results, and review investment memos. All outputs are generated by large language models
              and automated web searches. They are indicative, not authoritative. You are responsible
              for any decisions you make based on information presented in this tool.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-text mb-3">No Financial Advice</h2>
            <p>
              Nothing on this platform constitutes financial, investment, or legal advice. No real
              investment decisions are executed through ScoutLayer. Trust Scores, screening axes, and
              investment memos are AI-generated analyses intended for demonstration purposes only. Do
              not treat them as a substitute for professional due diligence.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-text mb-3">Data Handling</h2>
            <p>
              Data you submit (company information, pitch deck links) is stored in MongoDB Atlas and
              processed through third-party AI services (Groq, OpenAI, Tavily) for screening and
              verification. See our <Link href="/privacy" className="text-action hover:underline">Privacy Policy</Link> for
              full details on data collection and processing.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-text mb-3">Changes to Terms</h2>
            <p>
              As a hackathon prototype, these terms may change without notice. Continued use of the
              platform after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-text mb-3">Contact</h2>
            <p>
              For questions about these terms, reach out via the project&apos;s GitHub repository or
              contact the builder directly through the hackathon organizers.
            </p>
          </section>
        </div>
      </article>
    </div>
  );
}
